name: sandbox
description: Widgetbook's own "Widgetbook" (i.e. a catalog for widgets built inside Widgetbook).
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.9.0
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  alchemist: ^0.7.0
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true
