name: sandbox
description: Widgetbook's own "Widgetbook" (i.e. a catalog for widgets built inside Widgetbook).
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.0.0-rc.2
  widgetbook_annotation: ^3.0.0-rc.2

dev_dependencies:
  build_runner: ^2.3.2
  widgetbook_generator: ^3.0.0-rc.2

flutter:
  uses-material-design: true
