include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Constructors
    - sort_unnamed_constructors_first
    - sort_constructors_first
    - prefer_const_constructors
    - use_key_in_widget_constructors

    # Imports
    - prefer_relative_imports
    - directives_ordering
    - combinators_ordering
    - depend_on_referenced_packages
    - avoid_web_libraries_in_flutter

    # Dependencies
    - sort_pub_dependencies

    # Style
    - prefer_single_quotes
    - require_trailing_commas
    - noop_primitive_operations

    # Types
    - unrelated_type_equality_checks
