include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "bricks"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "examples/screen_util_example/lib/main.widgetbook.dart" # The only generated .widgetbook.dart file
    - "**/example/*.dart"
    - "**/example/**/*.dart"

linter:
  rules:
    public_member_api_docs: false