name: widgetbook
repository: https://github.com/widgetbook/widgetbook

packages:
  - packages/**
  - examples/**
  - sandbox/

command:
  version:
    branch: main

scripts:
  test-coverage:
    run: melos exec --dir-exists=test --flutter -- "flutter test --coverage && genhtml ./coverage/lcov.info --output-directory ./coverage/out"
    description: Run flutter test with coverage and generates coverage report

  generate:
    run: melos exec $MELOS_FILTERS -c 1 --depends-on="build_runner" -- "dart pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files.
