name: admin_app
description: An admin app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  shared_ui:
    path: ../../packages/shared_ui

flutter:
  uses-material-design: true
