name: full_example
description: An example project that demonstrates all Widgetbook features.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^4.0.0-alpha.2

dev_dependencies:
  build_runner: ^2.4.7
  widgetbook_generator: ^4.0.0-alpha.2

flutter:
  uses-material-design: true
