name: screen_util_example
description: An example project that demonstrates how to use Widgetbook with the flutter_screenutil package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  widgetbook: ^3.7.0

dev_dependencies:
  build_runner: ^2.4.7
  widgetbook_generator: ^3.6.0

flutter:
  uses-material-design: true
