name: screen_util_example
description: An example project that demonstrates how to use Widgetbook with the flutter_screenutil package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  widgetbook: ^3.7.1

flutter:
  uses-material-design: true
