name: screen_util_example
description: An example on how to use flutter_screenutil with Widgetbook.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  widgetbook: ^3.0.0-rc.1
  widgetbook_annotation: ^3.0.0-rc.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.0.0-rc.1

flutter:
  uses-material-design: true
