name: widgetbook_cli
description: A CLI to interact with Widgetbook Cloud.
version: 3.0.0-rc.2
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_cli
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_cli

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  archive: ^3.3.0
  args: ^2.3.0
  ci: ^0.1.0
  collection: ^1.15.0
  dio: ^5.1.1
  file: ^6.1.2
  freezed_annotation: ^2.0.3
  http_parser: ^4.0.1
  mason_logger: ^0.2.5
  meta: ^1.8.0
  path: ^1.8.2
  pub_updater: ^0.3.0 
  pubspec: ^2.3.0
  test: ^1.12.1
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.1.10
  build_version: ^2.1.1
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  test_descriptor: ^2.0.0

executables:
  widgetbook: cli_production
  widgetbook_staging: cli_staging
  widgetbook_debug: cli_debug
