name: widgetbook_cli
description: A CLI to interact with Widgetbook Cloud.
version: 3.0.0-rc.3
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_cli
repository: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_cli
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io
topics: [widgetbook, storybook, ui, tool, cli]

screenshots:
  - description: 'Widgetbook Logo'
    path: assets/logo.png

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  archive: ^3.3.0
  args: ^2.3.0
  ci: ^0.1.0
  collection: ^1.15.0
  dio: ^5.1.1
  file: ^6.1.2
  http_parser: ^4.0.1
  mason_logger: ^0.2.5
  meta: ^1.8.0
  path: ^1.8.2
  pub_updater: ^0.3.0 
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.1.10
  build_version: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.12.1
  test_descriptor: ^2.0.0

executables:
  widgetbook: cli_production
  widgetbook_staging: cli_staging
  widgetbook_debug: cli_debug
