name: widgetbook_playground
description: A playground to streamline shared_ui with Widgetbook
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook_annotation: ^3.0.0
  widgetbook: ^3.2.0
  shared_ui:
    path: ../packages/shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook_generator: ^3.1.0
  build_runner:

flutter:
  uses-material-design: true
