builders:
  use_case_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["useCaseBuilder"]
    build_extensions: { ".dart": [".usecase.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":app_builder", ":telemetry"]
    build_to: cache

  app_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["appBuilder"]
    build_extensions: { ".dart": [".directories.g.dart"] }
    auto_apply: dependents
    build_to: source

  telemetry:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["reportTelemetry"]
    build_extensions: { ".directories.g.dart": [".track"] }
    required_inputs: [".directories.g.dart"]
    auto_apply: root_package
    build_to: cache
    defaults:
      options:
        debug: false
