builders:
  use_case_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["useCaseBuilder"]
    build_extensions: { ".dart": [".usecase.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":app_builder"]
    build_to: cache

  app_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["appBuilder"]
    build_extensions: { ".dart": [".directories.g.dart"] }
    auto_apply: dependents
    build_to: source

  experimental_story_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["storyBuilder"]
    runs_before: [":experimental_components_builder"]
    build_extensions: { ".stories.dart": [".stories.book.dart"] }
    auto_apply: none # Disabled by default
    build_to: source
    defaults:
      generate_for:
        - lib/**.stories.dart

  experimental_components_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["componentsBuilder"]
    build_extensions: { ".stories.dart": [".dart"] }
    runs_before: [":telemetry"]
    auto_apply: none # Disabled by default
    build_to: source

  telemetry:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["reportTelemetry"]
    build_extensions: { ".book.dart": [".track"] }
    required_inputs: [".book.dart"]
    auto_apply: root_package
    build_to: cache
    defaults:
      options:
        debug: false
      generate_for:
        - lib/components.book.dart
