builders:
  use_case_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["useCaseBuilder"]
    build_extensions: { ".dart": [".usecase.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":widgetbook_builder"]
    build_to: cache

  widgetbook_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["widgetbookBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source