name: widgetbook_generator
description: A package to automate setup and maintenance of the widgetbook package by using code generation.
version: 3.0.0
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_generator
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ">=5.10.0 <7.0.0"
  build: ^2.1.0
  collection: ^1.15.0
  glob: ^2.0.2
  json_annotation: ^4.8.0
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: ^1.1.0
  widgetbook_annotation: ^3.0.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.1
