name: Package Workflow

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      post_checkout:
        required: false
        type: string
        default: ""
      run_pana:
        required: false
        type: boolean
        default: true

jobs:
  doctor:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Post Checkout Script
        if: "${{ inputs.post_checkout != '' }}"
        run: ${{ inputs.post_checkout }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Bootstrap Workspace
        working-directory: ${{ github.workspace }}
        run: flutter pub get

      - name: Bootstrap Package
        run: |
          PACKAGE_NAME=$(head -1 pubspec.yaml | cut -c7-)
          melos bootstrap --scope=$PACKAGE_NAME --include-dependencies

      - name: Check Formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze . --fatal-infos

      - name: Run Tests
        run: flutter test --coverage

      - name: Install pana
        if: inputs.run_pana
        run: |
          dart pub global activate pana
          sudo apt-get update
          sudo apt-get install webp # Needed for screenshots validation

      - name: Check Package Score
        if: inputs.run_pana
        run: pana . --no-warning --exit-code-threshold 0

  publish:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: pub.dev

    permissions:
      id-token: write

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sets the GitHub-signed OIDC token
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Bootstrap Workspace
        working-directory: ${{ github.workspace }}
        run: flutter pub get

      - name: Bootstrap Package
        run: |
          PACKAGE_NAME=$(head -1 pubspec.yaml | cut -c7-)
          melos bootstrap --scope=$PACKAGE_NAME --include-dependencies

      - name: Publish
        run: dart pub publish --force
