name: Upload build
on:
  push:
    branches:
      - staging
      - main
      - widgetbook-3
jobs:
  build:
    defaults:
      run:
        working-directory: ./widgetbook_for_widgetbook

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable melos
        run: flutter pub global activate melos

      - name: Get packages 
        run: melos bootstrap

      - name: Run build runner for packages
        run: melos run generate

      - name: Run build runner for app
        run: flutter pub run build_runner build -d

      - name: Build Website
        run: flutter build web -t lib/widgetbook.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate --source path ../packages/widgetbook_cli

      - name: Upload Widgetbook
        run: |
          widgetbook publish \
                --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }} \
                --repository \
                $GITHUB_REPOSITORY \
                --actor \
                $GITHUB_ACTOR
