name: Upload Review

on:
  pull_request:

jobs:
  _:
    # Don't run on PRs made by external contributors,
    # since secrets are not available in this case.
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/_upload.yml
    secrets: inherit
    with:
      mode: review
