name: widgetbook_core

on:
  pull_request:
    paths:
      - packages/widgetbook_core/**
      - .github/workflows/widgetbook-core.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main
    tags:
      - widgetbook_core-v[0-9]+.[0-9]+.[0-9]+*

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook_core
