name: widgetbook_annotation

on:
  pull_request:
    paths:
      - packages/widgetbook_annotation/**
      - .github/workflows/widgetbook-annotation.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook_annotation
