name: widgetbook_models

on:
  pull_request:
    paths:
      - packages/widgetbook_models/**
      - .github/workflows/widgetbook-models.yaml
  push:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: packages/widgetbook_models
      setup: |
        dart pub global activate melos
        melos bootstrap --scope='widgetbook_models'
