name: widgetbook_cli

on:
  pull_request:
    paths:
      - packages/widgetbook_cli/**
      - .github/workflows/widgetbook-cli.yaml
  push:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: packages/widgetbook_cli
      analyze_directories: bin test
      setup: |
        dart pub global activate melos
        melos bootstrap --scope='widgetbook_cli'
