name: widgetbook

on:
  pull_request:
    paths:
      - packages/widgetbook/**
      - .github/workflows/widgetbook.yaml
  push:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: packages/widgetbook
      min_coverage: 77
      test_optimization: false
      setup: |
        dart pub global activate melos
        melos bootstrap
        melos run generate
