name: widgetbook

on:
  pull_request:
    paths:
      - packages/widgetbook/**
      - .github/workflows/widgetbook.yaml
  push:
    branches:
      - main

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook
