name: widgetbook_generator

on:
  pull_request:
    paths:
      - packages/widgetbook_generator/**
      - .github/workflows/widgetbook-generator.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook_generator
