name: widgetbook_models

on:
  pull_request:
    paths:
      - packages/widgetbook_models/**
      - .github/workflows/widgetbook-models.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook_models

