name: widgetbook_cli

on:
  pull_request:
    paths:
      - packages/widgetbook_cli/**
      - .github/workflows/widgetbook-cli.yaml
      - .github/workflows/_package.yml
  push:
    branches:
      - main

jobs:
  _:
    uses: ./.github/workflows/_package.yml
    with:
      working_directory: packages/widgetbook_cli
      post_checkout: |
        # Setup dummy Git user
        git config --global user.email "john@doe.co"
        git config --global user.name "John Doe"