name: widgetbook_generator

on:
  pull_request:
    paths:
      - packages/widgetbook_generator/**
      - .github/workflows/widgetbook-generator.yaml
  push:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      working_directory: packages/widgetbook_generator
      min_coverage: 67
      setup: |
        dart pub global activate melos
        melos bootstrap
        melos run generate
